# aicage settings
image_registry: ghcr.io
image_registry_api_url: https://ghcr.io/v2
image_registry_api_token_url: https://ghcr.io/token?service=ghcr.io&scope=repository
image_repository: aicage/aicage
default_image_base: ubuntu
images_metadata_release_api_url: https://api.github.com/repos/aicage/aicage-image/releases/latest
images_metadata_asset_name: images-metadata.yaml
images_metadata_download_retries: 3
images_metadata_retry_backoff_seconds: 1.5
